SELECT a.*
FROM ACCOUNTS AS a INNER JOIN
(SELECT SOURCE_ID, SUM(AMOUNT)
FROM TRANSFERS
WHERE TRANSFER_TIME >= '2019-01-01' AND t.TARGET_ID <> t.SOURCE_ID
GROUP BY SOURCE_ID
HAVING SUM(AMOUNT) > 1000) as t on t.SOURCE_ID = a.ID;


SELECT a.*, SUM(t.AMOUNT)
FROM ACCOUNTS as a, TRANSFERS as t
WHERE t.TRANSFER_TIME >= '2019-01-01' AND t.SOURCE_ID == a.ID AND t.TARGET_ID <> t.SOURCE_ID
GROUP BY t.SOURCE_ID
HAVING SUM(AMOUNT) > 1000;