CREATE TABLE TRANSFERS (
  ID INTEGER PRIMARY KEY NOT NULL,
  SOURCE_ID INTEGER REFERENCES ACCOUNTS (ID),
  TARGET_ID INTEGER REFERENCES ACCOUNTS (ID),
  AMOUNT DECIMAL NOT NULL,
  TRANSFER_TIME TIMESTAMP
);